service: salon-app-booking-api


frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-ignore
custom:
  pythonRequirements:
    useDownloadCache: false

  wsgi:
    app: application.app

